# Generated by Django 2.2.1 on 2019-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190530_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
